document.addEventListener("DOMContentLoaded", () => {
  const container = document.createElement("div");
  container.innerHTML = `
    <h1>Welcome</h1>
    <p>This page was generated by script.js.</p>
  `;
  document.body.appendChild(container);
});
